# package.json repo à changer

tasks:
  - name: Configuration
    before: npm install -g ts-node
    init: |
      shopt -s dotglob
      bash .gitpod-config/bash.sh
      node .gitpod-config/bash.js
      git push
      gp sync-done build
      
  - name: Creation of branches
    init: |
      gp sync-await build
      git checkout -b prod
      git push -u origin prod
      git checkout -b staging
      git push -u origin staging
      git checkout -b upgrade
      git push -u origin upgrade
      git checkout main

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-ceintl.vscode-language-pack-fr
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - fabiospampinato.vscode-todo-plus
    - dbaeumer.vscode-eslint
    - tabnine.tabnine-vscode
    - codezombiech.gitignore
    - foxundermoon.shell-format
    - redhat.vscode-xml
    - hbenl.test-adapter-converter
