name: Check secret

on: 
  workflow_call:
    outputs:
      defined: 
        value: ${{ jobs.job.outputs.defined }}
    inputs:
      secret:
        type: string
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.test.outputs.defined }}
    steps:
    - id: test
      name: Test
      if: "${{ env.MY_KEY != '' }}"
      run: echo "::set-output name=defined::true"
      env:
        MY_KEY: ${{ inputs.secret }}