name: Publish-beta
on:
  push:
    branches:
      - beta

jobs:
  publish:
    name: Publish-beta
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.6

      - name: Setup node for publication
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@bemedev'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{
            hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - uses: JS-DevTools/npm-publish@v3
        id: publish
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: all
          tag: beta

      - name: Check - updated
        if: ${{ steps.publish.outputs.type }}
        run:
          echo "${{ steps.publish.outputs.name }} Version changed from ${{
          steps.publish.outputs.old-version }} to ${{
          steps.publish.outputs.version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.type }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"
